import { gql } from "@apollo/client";

export const GET_PRODUCT_NUTRITION_DATA_QUERY = gql(`
  query GetProductNutritionData($productId: ID!) {
    getProductNutritionData(productId: $productId) {
      productId
      servingSize
      servingSizeUnit
      servingSizeValue
      ingredientText
      ingredientList
      nutriments {
        salt
        salt100g
        saltValue
        saltServing
        saltUnit
        sugars
        sugars100g
        sugarsValue
        sugarsServing
        sugarsUnit
        iron
        iron100g
        ironValue
        ironServing
        ironUnit
        ironLabel
        calcium
        calcium100g
        calciumValue
        calciumServing
        calciumUnit
        calciumLabel
        cholesterol100g
        saturatedFat
        saturatedFat100g
        saturatedFatValue
        saturatedFatServing
        saturatedFatUnit
        fat
        fat100g
        fatValue
        fatServing
        fatUnit
        transFat
        transFat100g
        transFatValue
        transFatServing
        transFatUnit
        transFatLabel
        vitaminA
        vitaminA100g
        vitaminAValue
        vitaminAServing
        vitaminAUnit
        vitaminALabel
        vitaminC
        vitaminC100g
        vitaminCValue
        vitaminCServing
        vitaminCUnit
        vitaminCLabel
        proteins
        proteins100g
        proteinsValue
        proteinsServing
        proteinsUnit
        fiber
        fiber100g
        fiberValue
        fiberServing
        fiberUnit
        carbohydrates
        carbohydrates100g
        carbohydratesValue
        carbohydratesServing
        carbohydratesUnit
        alcohol
        alcohol100g
        alcoholValue
        alcoholServing
        alcoholUnit
        sodium
        sodium100g
        sodiumValue
        sodiumServing
        sodiumUnit
        potassium100g
        polyunsaturatedFat100g
        monounsaturatedFat100g
        novaGroup
        novaGroup100g
        novaGroupServing
        energy
        energy100g
        energyValue
        energyServing
        energyUnit
        energyKcal
        energyKcal100g
        energyKcalValue
        energyKcalServing
        energyKcalUnit
        nutritionScoreFr
        nutritionScoreFr100g
        nutritionScoreFrServing
        nutritionScoreUk
        nutritionScoreUk100g
        nutritionScoreUkServing
      }
      vegan
      vegetarian
      glutenFree
      lactoseFree
      halal
      kosher
      createdAt
      updatedAt
    }
  }
`);
